
// -*- C++ -*-
// $Id$
// This is file was automatically generated by \$ACE_ROOT/bin/make_release.py

#define DAnCE_MAJOR_VERSION 1
#define DAnCE_MINOR_VERSION 2
#define DAnCE_BETA_VERSION 0
#define DAnCE_VERSION "1.2a_p17"
#define DAnCE_OCI_PATCHLEVEL 17
#define DAnCE_OCI_REV a
