# Contains configuration variables for the FindOpenDDS cmake module based on
# detected defaults and/or user-supplied switches. Feel free to edit them as
# necessary, but keep in mind that they will be moved to config.cmake.bak.*
# the next time the $DDS_ROOT/configure script is executed.
#
# THIS FILE WAS AUTO-GENERATED BY: ./configure 
#

set(OPENDDS_ACE "/Users/thiennd/Desktop/study-documents/20192/20192-excercies/DistributedSystem/OpenDDS-3.14/ACE_wrappers")
set(OPENDDS_BUILT_IN_TOPICS ON)
set(OPENDDS_CMAKE "/usr/bin/cmake")
set(OPENDDS_COMPILER "clang++")
set(OPENDDS_CONFIGH "")
set(OPENDDS_CONTENT_FILTERED_TOPIC ON)
set(OPENDDS_CONTENT_SUBSCRIPTION ON)
set(OPENDDS_HOST "macosx")
set(OPENDDS_INLINE ON)
set(OPENDDS_MACROS "")
set(OPENDDS_MULTI_TOPIC ON)
set(OPENDDS_OBJECT_MODEL_PROFILE ON)
set(OPENDDS_OPTIMIZE OFF)
set(OPENDDS_OWNERSHIP_KIND_EXCLUSIVE ON)
set(OPENDDS_OWNERSHIP_PROFILE ON)
set(OPENDDS_PERSISTENCE_PROFILE ON)
set(OPENDDS_QUERY_CONDITION ON)
set(OPENDDS_SECURITY OFF)
set(OPENDDS_SOLUTION_FILE "DDS_TAOv2.sln")
set(OPENDDS_SUPPRESS_ANYS ON)
set(OPENDDS_TAO "/Users/thiennd/Desktop/study-documents/20192/20192-excercies/DistributedSystem/OpenDDS-3.14/ACE_wrappers/TAO")
set(OPENDDS_TARGET "macosx")
