# OpenDDS configure script: ./configure 
export DANCE_ROOT := unused
export DYLD_LIBRARY_PATH := ${DYLD_LIBRARY_PATH}:/Users/thiennd/Desktop/study-documents/20192/20192-excercies/DistributedSystem/OpenDDS-3.14/ACE_wrappers/lib:/Users/thiennd/Desktop/study-documents/20192/20192-excercies/DistributedSystem/OpenDDS-3.14/lib
export CIAO_ROOT := unused
export ACE_ROOT := /Users/thiennd/Desktop/study-documents/20192/20192-excercies/DistributedSystem/OpenDDS-3.14/ACE_wrappers
export PATH := ${PATH}:/Users/thiennd/Desktop/study-documents/20192/20192-excercies/DistributedSystem/OpenDDS-3.14/ACE_wrappers/bin:/Users/thiennd/Desktop/study-documents/20192/20192-excercies/DistributedSystem/OpenDDS-3.14/bin
export TAO_ROOT := /Users/thiennd/Desktop/study-documents/20192/20192-excercies/DistributedSystem/OpenDDS-3.14/ACE_wrappers/TAO
export DDS_ROOT := /Users/thiennd/Desktop/study-documents/20192/20192-excercies/DistributedSystem/OpenDDS-3.14
export MPC_ROOT := /Users/thiennd/Desktop/study-documents/20192/20192-excercies/DistributedSystem/OpenDDS-3.14/ACE_wrappers/MPC
include GNUmakefile.dist
